{{flutter_js}}
{{flutter_build_config}}

// Custom bootstrap (replaces Flutter's default one): the same loader call
// minus `serviceWorkerSettings` — Flutter's own service worker is deprecated
// and only unregisters itself. The app's real offline service worker (sw.js,
// generated by tool/generate_service_worker.dart) is registered from
// index.html instead.
_flutter.loader.load();
